services:
  keycloak:
    container_name: keycloak-ms
    image: quay.io/keycloak/keycloak:26.2.5
    ports:
      - "9098:8080"
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
    networks:
      - microservice-net
    command:
      - "start-dev"

networks:
  microservice-net:
    driver: bridge